Feat/creator
Vitruveo/vtru-studio-api pull request #2
Opened 2023-12-13 18:04 UTC by m-paice

add controllers and models: 
- assets
- creators
- roles
- permissions

2023-12-13 18:15 UTC, nsfilho commented on src/constants/login.ts
> +    'd-631740bd4eae4beea96b97b83def0bf7';
@m-paice por favor, remover do inline e colocar no arquivo .env (o mesmo se aplica para as outras linhas deste arquivo que estao assim).....

2023-12-13 18:19 UTC, nsfilho commented on src/features/creators/controller/core.ts
> +        });
tipar o retorno @m-paice

2023-12-13 18:20 UTC, nsfilho commented on src/features/creators/controller/core.ts
> +        });
tipar o retorno @m-paice

2023-12-13 18:20 UTC, nsfilho commented on src/features/creators/controller/core.ts
> +        });
tipar o retorno @m-paice

2023-12-13 18:20 UTC, nsfilho commented on src/features/creators/controller/core.ts
> +        });
tipar o retorno @m-paice

2023-12-13 18:20 UTC, nsfilho commented on src/features/creators/controller/core.ts
> +        });
tipar o retorno @m-paice

2023-12-13 18:20 UTC, nsfilho commented on src/features/creators/controller/core.ts
> +        });
tipar o retorno @m-paice

2023-12-13 18:21 UTC, nsfilho commented on src/features/creators/controller/core.ts
> +        });
tipar o retorno @m-paice

2023-12-13 18:21 UTC, nsfilho commented on src/features/creators/controller/core.ts
> +        });
tipar o retorno @m-paice

2023-12-13 18:22 UTC, nsfilho commented on src/features/creators/controller/login.ts
> +import { model } from '..';
aqui e na linha de 9 a 15 estao sendo importadas as mesmas coisas, 2 vezes. Por favor, corrigir.
@m-paice

2023-12-13 18:24 UTC, nsfilho commented on src/features/creators/controller/login.ts
> +const emailValidation = z.string().email().min(1).max(64);
quando eh utilizado o email() nao eh preciso definir um min (visto que nao esta como nullable) e nem um max (visto que o e-mail pode ser de um sistema tipo: apple de seguranca).

2023-12-13 18:27 UTC, nsfilho commented on src/features/creators/controller/login.ts
> +                'login.codeHash': encryptCode(code),
'e preciso adicionar uma validade para o token de ateh 1 hora para o click em um campo, como por exemplo: 'login.validUntil' e nesta query, vc utiliza um $gt da hora atual.

Assim vc nem precisa tratar este campo no futuro. @Marcos-Barboza @m-paice

2023-12-13 18:30 UTC, nsfilho commented on src/features/creators/controller/login.ts
> +                message: 'Login failed: invalid code',
a mensagem precisa ser mais clara, code or email invalid or was expired. @m-paice

2023-12-13 18:31 UTC, nsfilho commented on src/features/creators/controller/login.ts
> +            ip: nanoid(),
o IP nao deve ser um nanoid, deve pegar do "req". @m-paice.

Alem disto este objeto deveria estar tipado. Para que nenhum campo ou nome fosse esquecido ou preenchido incorretamente.

2023-12-13 18:34 UTC, nsfilho commented on src/features/creators/controller/login.ts
> +        console.log({ template, code, email });
remover este console log @m-paice

2023-12-13 18:37 UTC, nsfilho commented on src/features/creators/controller/login.ts
> +route.get('/logout', async (req, res) => {
no logout devemos remover do redis (do hashset <token>: <id usuario>) este jwt para que ele nao possa mais realizar operacoes.

no validate (middleware) deve ser checado se este token esta no hashset. @m-paice

2023-12-13 18:37 UTC, nsfilho commented on src/features/creators/controller/login.ts
> +        res.json({
antes desta linha deve ser adicionado ao redis, no hashset <token>:<usuario> este login.
@m-paice

2023-12-14 18:59 UTC, nsfilho requested changes
Tem uns pontos criticos de seguranca que precisam ser revisados.

2023-12-14 18:59 UTC, nsfilho commented on src/features/assets/controller/core.ts
> +        } as APIResponse<model.Assets | null>);
Caso um asset nao seja localizado o correto nao eh voltar um 200 como status code, e sim 404.
precisa ser tratado com um `if`. E ao inves de chamar a variavel de `assets`, visto ser soh um, o ideal eh chamar de `asset`.

2023-12-14 18:59 UTC, nsfilho commented on src/features/assets/model/db.ts
> +import {
usar import type

2023-12-14 18:59 UTC, nsfilho commented on src/features/creators/controller/core.ts
> +        } as APIResponse<model.CreatorDocument | null>);
fazer o if do `creator` para responder 404, caso nao seja encontrado o creator.

2023-12-14 18:59 UTC, nsfilho commented on src/features/creators/controller/core.ts
> +            message: 'Exist username success',
talvez a mensagem pudesse ser Checked username with success

2023-12-14 18:59 UTC, nsfilho commented on src/features/creators/controller/core.ts
> +            message: 'Exist email success',
Checked email with success

2023-12-14 18:59 UTC, nsfilho commented on src/features/creators/controller/core.ts
> +        const creator = await model.addEmailCreator({
isto nao pode ser feito assim, senao um usuario pode adicionar seu e-mail no de outra pessoa, e dai logar como outro usuario. @m-paice 

**Este eh um ponto critico!!**

2023-12-14 18:59 UTC, nsfilho commented on src/features/creators/controller/core.ts
> +        console.log({ template, code, email });
remover este console log.

2023-12-14 18:59 UTC, nsfilho commented on src/features/creators/controller/core.ts
> +route.post('/:email/email/sendCode', async (req, res) => {
soh para simplificar o nome (e nao ficar tao fora do rest), o que acha de
/:email/sendCode apenas?

2023-12-14 18:59 UTC, nsfilho commented on src/features/creators/controller/core.ts
> +route.post('/:email/email/verifyCode', async (req, res) => {
oh para simplificar o nome (e nao ficar tao fora do rest), o que acha de
/:email/verifyCode apenas?

2023-12-14 18:59 UTC, nsfilho commented on src/features/creators/controller/core.ts
> +                emails: { $elemMatch: { email, codeHash: encryptCode(code) } },
precisa validar se jah esta expirado o token, ... o ideal eh que para cada token gerado, seja dada uma data de expiracao de 30 minutos. @m-paice

2023-12-14 18:59 UTC, nsfilho commented on src/features/creators/controller/core.ts
> +                emails: { $elemMatch: { email, codeHash: encryptCode(code) } },
sei que jah faria isto, mas o tempo deve ser especificado em uma variavel de ambiente. O quando de minutos deve ser considerado como expirado.

2023-12-14 18:59 UTC, nsfilho commented on src/features/creators/controller/core.ts
> +route.post('/request/upload', async (req, res) => {
o que eh este request upload? eh da foto do profile? se sim o ideal para a rota seria:
/profile/upload

Porque tudo que eh solicitado a api, de alguma forma, acaba sendo um request....

2023-12-14 18:59 UTC, nsfilho commented on src/features/creators/controller/core.ts
> +        const extension = mimetype.split('/')[1];
O mimetype.split nao vai retornar a extensao do arquivo (nao necessariamente). Idealmente utilize o pacote: https://www.npmjs.com/package/mime

Razoes: text/plain, a extensao eh txt ou "plain"? este eh soh um dos muitos casos por exemplo

2023-12-14 18:59 UTC, nsfilho commented on src/features/creators/controller/core.ts
> +            JSON.stringify({ key, creatorId: userId })
precisa ter um identificador desta solicitacao, a qual, recomendo que fosse o transaction (para manter uma logica)

2023-12-14 18:59 UTC, nsfilho commented on src/features/creators/controller/login.ts
> +import { LoginHistory } from '../model/types';
usar import type

2023-12-14 18:59 UTC, nsfilho commented on src/features/creators/controller/login.ts
> +const logger = debug('features:creators:controller');
neste trecho tem o "login" a mais no path...

2023-12-14 18:59 UTC, nsfilho commented on src/features/creators/controller/login.ts
> +route.post('/otpConfirm', async (req, res) => {
Utilizaria o mesmo nome que ja foi usado em outros lugares, como verifyCode

2023-12-14 18:59 UTC, nsfilho commented on src/features/creators/controller/login.ts
> +        const creator = await findOneCreator({
verificar se o codigo jah expirou (mesmo caso jah citado)

2023-12-14 18:59 UTC, nsfilho commented on src/features/creators/controller/login.ts
> +        const creatorUpdated = await findOneCreator({
no update vc jah pode receber como resposta o registro modificado, ao inves de fazer uma segunda solicitacao no mongo (eh um parametro). @m-paice

2023-12-14 18:59 UTC, nsfilho commented on src/features/creators/controller/login.ts
> +        if (!creator) {
adicionar o expire do code

2023-12-14 18:59 UTC, nsfilho commented on src/features/creators/model/db.ts
> +import {
usar import types

2023-12-14 18:59 UTC, nsfilho commented on src/features/creators/model/db.ts
> +export const createCreator = async ({ creator }: CreateCreatorParams) => {
quem esta preenchendo os campos do framework?

2023-12-14 18:59 UTC, nsfilho commented on src/features/creators/model/db.ts
> +export const deleteCreator = async ({ id }: DeleteCreatorParams) => {
somente um user ou o proprio creator pode usar

2023-12-14 21:50 UTC, m-paice commented on src/features/creators/controller/login.ts
> +        console.log({ template, code, email });
Iremos manter o log enquanto não concluir o envio do codigo via email.

2023-12-20 18:02 UTC, merged